version: '3.9'

services:
  postgresdb:
    container_name: ntnu_db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ntnu
      POSTGRES_USER: user
      POSTGRES_DB: ntnu_db
    volumes:
      - ./data/dbfiles:/var/lib/postgresql/data
    ports:
      - 5432:5432

  postgresdb2:
    container_name: ntnu_db_2
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ntnu
      POSTGRES_USER: user
      POSTGRES_DB: ntnu_db2
    volumes:
      - ./data/dbfiles2:/var/lib/postgresql/data
    ports:
      - 5433:5432

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: password
