version: '3.3'
services:
  postgresdb:
    container_name: ntnu_db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ntnu
      POSTGRES_USER: user
      POSTGRES_DB: ntnu_db
    volumes:
      - ./dbfiles:/var/lib/postgresql/data
    ports:
      - 5432:5432
    expose:
      - 5432
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@ntnu.no
      PGADMIN_DEFAULT_PASSWORD: ntnu
    ports:
      - "8080:80"